services:
  caddy:
    container_name: caddy
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - data:/data
      - config:/config
    networks:
      - services
      - default

volumes:
  data:
  config:

networks:
  services:
    external:
      name: services
